name: apiverve_airportcodeconverter
description: Airport Code Converter is a simple tool for converting between IATA (3-letter) and ICAO (4-letter) airport codes. Submit either format and get the corresponding code back.
version: 1.1.14
homepage: https://apiverve.com/marketplace/airportcodeconverter?utm_source=dart&utm_medium=homepage
repository: https://github.com/apiverve/airportcodeconverter-api/tree/main/dart

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  http: ^1.1.0
  http_parser: ^4.0.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
